name: Java CI with Maven and Allure

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests
      run: mvn clean test
      continue-on-error: true

    - name: Debug allure results
      run: |
        ls -R target/allure-results || echo "allure-results пустая"

    - name: Install Allure CLI
      run: |
        sudo apt-add-repository ppa:qameta/allure -y
        sudo apt-get update
        sudo apt-get install allure -y

    - name: Generate Allure Report
      run: |
        allure generate target/allure-results -o allure-report --clean
        ls -l allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
